name: Release

on:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: zip custom component
        run: |
          cd ${{ github.workspace }}/custom_components/virtual_devices
          zip -r virtual_devices.zip ./

      - name: upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/virtual_devices/virtual_devices.zip
          asset_name: virtual_devices.zip
          tag: ${{ github.ref }}
          overwrite: true
